services:
  - type: web
    name: whatsapp-ai-bot
    plan: free
    runtime: python

    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-bot-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false


databases:
  - name: whatsapp-bot-db
    plan: free
