# Generated by Django 6.0.5 on 2026-06-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(
                    db_index=True, max_length=20, unique=True)),
                ('owner_name', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('truck_number', models.CharField(
                    blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
