# Generated by Django 6.0.6 on 2026-06-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_broadcasttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(
                    db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
