# Generated by Django 6.0.6 on 2026-07-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_adcampaign_fleetcustomer_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'template_name',
                    models.CharField(
                        help_text='Approved Meta template name (e.g. gps_tracking_device)',
                        max_length=100,
                        unique=True)),
                ('description',
                 models.CharField(blank=True,
                                  help_text='Brief description/label shown in dropdown',
                                  max_length=255)),
                ('has_variables', models.BooleanField(default=False,
                 help_text='Check if this template has placeholders (e.g., {{1}} for Customer Name, {{2}} for Vehicle Number)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
