# Generated by Django 5.1.5 on 2026-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_whatsapptemplate_languages_alter_adcampaign_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasttask',
            name='language_code',
            field=models.CharField(default='en_US', max_length=10),
        ),
    ]
