# Generated by Django 5.1.5 on 2026-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_whatsapptemplate_has_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_file',
            field=models.FileField(blank=True, help_text='Upload header file (image, video, document) from local system', null=True, upload_to='whatsapp_templates/'),
        ),
    ]
