# Generated by Django 5.1.5 on 2026-07-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_whatsapptemplate_header_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_media_id',
            field=models.CharField(
                blank=True,
                default='',
                help_text="Meta's media ID once uploaded",
                max_length=100),
        ),
    ]
