# Generated by Django 5.1.5 on 2026-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_whatsapptemplate_header_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='media_id_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the Meta media ID was last refreshed/uploaded', null=True),
        ),
    ]
