# Generated by Django 5.1.5 on 2026-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_whatsapptemplate_media_id_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='custom_system_prompt',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Custom instructions to inject into the AI agent prompt when a customer responds to this template.'),
        ),
    ]
