# Generated by Django 5.1.5 on 2026-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_agentnotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='category',
            field=models.CharField(choices=[('utility', 'Utility'), ('marketing', 'Marketing'), ('authentication', 'Authentication')], default='marketing', help_text='Template category (e.g. marketing, utility)', max_length=50),
        ),
    ]
