# Generated by Django 5.1.5 on 2026-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_fleetcustomer_is_bot_paused_alter_adcampaign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
    ]
