# Generated by Django 6.0.5 on 2026-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_chatmessage_message_id_chatmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetcustomer',
            name='bot_paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the bot was paused', null=True),
        ),
    ]
