# Generated by Django 5.1.5 on 2026-07-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_fleetcustomer_bot_paused_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnotificationlog',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='agentnotificationlog',
            index=models.Index(fields=['phone_number', '-created_at'], name='bot_agentno_phone_n_cca3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['phone_number', '-id'], name='bot_chatmes_phone_n_b504cd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['phone_number', '-timestamp'], name='bot_chatmes_phone_n_fae51e_idx'),
        ),
    ]
