# Generated by Django 5.1.5 on 2026-07-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_backfill_agent_notification_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='var_count',
            field=models.IntegerField(default=0, help_text='Exact number of body placeholders/variables expected (0, 1, or 2)'),
        ),
        migrations.AlterField(
            model_name='broadcasttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
