# Generated by Django 5.1.5 on 2026-07-20 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_whatsapptemplate_var_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasttask',
            name='delivered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcasttask',
            name='rate_limit_per_sec',
            field=models.IntegerField(default=50, help_text='Target messages per second (max 80 for Meta standard Cloud API)'),
        ),
        migrations.AddField(
            model_name='broadcasttask',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('truck_number', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('opt_out', 'Opted Out')], db_index=True, default='pending', max_length=20)),
                ('wamid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='bot.broadcasttask')),
            ],
            options={
                'indexes': [models.Index(fields=['task', 'status'], name='bot_broadca_task_id_5b1ca0_idx'), models.Index(fields=['phone_number', 'status'], name='bot_broadca_phone_n_b6035f_idx')],
            },
        ),
    ]
