# Generated by Django 5.1.5 on 2026-07-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_broadcasttask_delivered_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='body_text',
            field=models.TextField(blank=True, default='', help_text='Template body content with optional placeholders like {{1}}, {{2}}'),
        ),
    ]
